#  Ejercicios de Numpy

1. mporta la librería de NumPy.

In [1]:
import numpy as np 

2. Crea un array de 1 dimension y 10 elementos.

In [2]:
dimension1 = np.random.randint(0,10, (10)) #creamos un array aleatorio con una dimensión, señalando la franja de números que queremos, entre 0 y 10
dimension1 

array([3, 8, 9, 9, 0, 0, 3, 7, 5, 7])

3. Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [3]:
array_contenedor = np.empty_like(dimension1, dtype = str) #creamos un array vacío que nos sirva de contenedor para insertar el resultado de nuestro bucle for
array_contenedor #este array está construido con las mismas características que el array inicial

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [4]:
for n in range(0, dimension1.shape[0]): #este bucle for nos permite iterar por el array inicial de una dimensión
    if dimension1[n] % 2 == 0:       #si en el array inicial se han generado números pares
        array_contenedor[n] = 'par'  #en el contenedor se nos creará 'par' en sustitución 

    else:                             #si en el array inicial se han generado números pares
        array_contenedor[n] = 'impar' #en el contenedor se nos creará 'impar' en sustitución 

print(array_contenedor) #por alguna razón sólo se imprimen las primeras letras

['i' 'p' 'i' 'i' 'p' 'p' 'i' 'i' 'i' 'i']


4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [5]:
array_contenedor.reshape(2,5) #con el método .reshape() modificamos a nuestro gusto el array

array([['i', 'p', 'i', 'i', 'p'],
       ['p', 'i', 'i', 'i', 'i']], dtype='<U1')

5. Extrae los elementos comunes de los siguientes arrays

In [6]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [7]:
np.intersect1d(array1, array2) #.intersec1d() sirve para extraer los elementos comunes de dos arrays, y el output nos eliminan los duplicados

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [8]:
np.setdiff1d(array1, array2) #.setdiffid nos extrae los elementos que estan en el array que le demos primero, comparándolo al segundo y extrayendo los diferentes

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [17]:
np.unique(array1, return_index= True ) #unique para ver qué valores únicos tenemos y su posición en el siguiente array

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 5, 8, 9]))

In [18]:
np.unique(array2, return_index= True ) #lo mismo para el array2

(array([ 2,  4,  7,  8,  9, 10]), array([1, 5, 0, 9, 6, 2]))

8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [11]:
dimension2 = np.random.randint(0, 50,(3,5))
dimension2 #creamos un array con números aleatorios en dos dimensiones

array([[15,  6, 23,  9, 29],
       [24,  4, 47, 43, 48],
       [26, 45, 18, 47, 28]])

In [12]:
dimension2.shape

(3, 5)

In [13]:
valores_d2 = [] #creamos lista vacía para ir acumulando los valores que queramos

for n in range(0, dimension2.shape[0]):  #comenzamos el bucle for en la dimensión 1, que corresponde al índice [0]
    for num in range(0, dimension2.shape[1]): #entramos en la dimensión 2, que corresponde al índice [1]
        if dimension2[n][num] < 10 or dimension2[n][num] >40 and dimension2[n][num] not in valores_d2: #le damos las condiciones que nos pide el enunciado
            valores_d2.append(dimension2[n][num]) #le pedimos que nos lo añada a la lista vacía para que luego nos aparezca

print(valores_d2)

[6, 9, 4, 47, 43, 48, 45]


9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [14]:
dimension3 = np.random.uniform(5, 10,(5,3)) #generamos con .uniform() un array de dos dimensiones con números aleatorios decimales de 5 a 10
dimension3

array([[5.88655295, 9.47089857, 5.39928952],
       [6.76868046, 8.34585781, 9.93645066],
       [9.47275951, 7.36244753, 5.70139255],
       [6.54213443, 6.21964205, 8.70311675],
       [9.6669039 , 5.6354175 , 5.83309975]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [15]:
dimension31 = np.random.randint(1, 20, (2, 4, 7))
dimension31

array([[[ 6, 12, 18, 15, 16, 11,  6],
        [19, 10, 13,  9, 12, 14, 18],
        [ 3, 10,  4,  4,  3,  1, 19],
        [ 1, 14, 17,  1,  3,  1, 16]],

       [[ 5, 11, 18,  3, 10, 16,  7],
        [ 9,  6, 19,  9, 18,  5,  4],
        [ 4,  4,  7,  5,  5, 19,  7],
        [12,  9, 14,  1, 19, 11,  4]]])

In [16]:
np.transpose(dimension31, (1, 2, 0))

array([[[ 6,  5],
        [12, 11],
        [18, 18],
        [15,  3],
        [16, 10],
        [11, 16],
        [ 6,  7]],

       [[19,  9],
        [10,  6],
        [13, 19],
        [ 9,  9],
        [12, 18],
        [14,  5],
        [18,  4]],

       [[ 3,  4],
        [10,  4],
        [ 4,  7],
        [ 4,  5],
        [ 3,  5],
        [ 1, 19],
        [19,  7]],

       [[ 1, 12],
        [14,  9],
        [17, 14],
        [ 1,  1],
        [ 3, 19],
        [ 1, 11],
        [16,  4]]])