#  Ejercicios de Numpy

1. mporta la librería de NumPy.

In [2]:
import numpy as np 

2. Crea un array de 1 dimension y 10 elementos.

In [3]:
dimension1 = np.random.randint(0,10, (10)) #creamos un array aleatorio con una dimensión, señalando la franja de números que queremos, entre 0 y 10
dimension1 

array([4, 9, 5, 6, 6, 9, 1, 3, 8, 1])

3. Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [4]:
array_contenedor = np.empty_like(dimension1, dtype = str) #creamos un array vacío que nos sirva de contenedor para insertar el resultado de nuestro bucle for
array_contenedor #este array está construido con las mismas características que el array inicial

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [5]:
for n in range(0, dimension1.shape[0]): #este bucle for nos permite iterar por el array inicial de una dimensión
    if dimension1[n] % 2 == 0:       #si en el array inicial se han generado números pares
        array_contenedor[n] = 'par'  #en el contenedor se nos creará 'par' en sustitución 

    else:                             #si en el array inicial se han generado números pares
        array_contenedor[n] = 'impar' #en el contenedor se nos creará 'impar' en sustitución 

print(array_contenedor) #por alguna razón sólo se imprimen las primeras letras

['p' 'i' 'i' 'p' 'p' 'i' 'i' 'i' 'p' 'i']


4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [6]:
array_contenedor.reshape(2,5) #con el método .reshape() modificamos a nuestro gusto el array

array([['p', 'i', 'i', 'p', 'p'],
       ['i', 'i', 'i', 'p', 'i']], dtype='<U1')

5. Extrae los elementos comunes de los siguientes arrays

In [7]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
np.intersect1d(array1, array2) #.intersec1d() sirve para extraer los elementos comunes de dos arrays, y el output nos eliminan los duplicados

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [9]:
np.setdiff1d(array1, array2) #.setdiffid nos extrae los elementos que estan en el array que le demos primero, comparándolo al segundo y extrayendo los diferentes

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [10]:
np.unique(array1, return_counts= True ) #unique para ver qué valores únicos tenemos y su posición en el siguiente array

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1]))

In [11]:
np.unique(array2, return_counts= True )

(array([ 2,  4,  7,  8,  9, 10]), array([2, 2, 2, 1, 2, 1]))

8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [12]:
dimension2 = np.random.randint(0, 50,(3,5))
dimension2 #creamos un array con números aleatorios en dos dimensiones

array([[30, 11,  0, 36, 11],
       [21, 24, 29, 22, 12],
       [35, 28, 33, 43, 21]])

In [13]:
dimension2.shape

(3, 5)

In [14]:
valores_d2 = [] #creamos lista vacía para ir acumulando los valores que queramos

for n in range(0, dimension2.shape[0]):  #comenzamos el bucle for en la dimensión 1, que corresponde al índice [0]
    for num in range(0, dimension2.shape[1]): #entramos en la dimensión 2, que corresponde al índice [1]
        if dimension2[n][num] < 10 or dimension2[n][num] >40 and dimension2[n][num] not in valores_d2: #le damos las condiciones que nos pide el enunciado
            valores_d2.append(dimension2[n][num]) #le pedimos que nos lo añada a la lista vacía para que luego nos aparezca

print(valores_d2)

[0, 43]


9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [15]:
dimension3 = np.random.uniform(5, 10,(5,3)) #generamos con .uniform() un array de dos dimensiones con números aleatorios decimales de 5 a 10
dimension3

array([[9.97835866, 7.05584053, 6.10724475],
       [5.4338532 , 7.90339848, 9.38491735],
       [7.69210019, 5.50015235, 6.51983391],
       [7.37789566, 7.59360403, 9.78293549],
       [6.7755998 , 9.23102363, 8.7102236 ]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [16]:
dimension31 = np.random.randint(1, 20, (2, 4, 7))
dimension31

array([[[ 7,  1, 15,  5,  9, 19, 16],
        [ 1,  5, 13,  3, 10, 14, 19],
        [15,  2,  7,  9,  4, 16,  8],
        [10, 15,  9, 19,  4,  3,  2]],

       [[ 8, 12,  5, 19,  6, 13, 17],
        [ 8,  1, 15,  4, 14,  3, 13],
        [ 3,  8,  9, 17,  2, 14, 16],
        [ 4,  8, 15, 15,  8, 15,  3]]])

In [17]:
np.transpose(dimension31, (1, 2, 0))

array([[[ 7,  8],
        [ 1, 12],
        [15,  5],
        [ 5, 19],
        [ 9,  6],
        [19, 13],
        [16, 17]],

       [[ 1,  8],
        [ 5,  1],
        [13, 15],
        [ 3,  4],
        [10, 14],
        [14,  3],
        [19, 13]],

       [[15,  3],
        [ 2,  8],
        [ 7,  9],
        [ 9, 17],
        [ 4,  2],
        [16, 14],
        [ 8, 16]],

       [[10,  4],
        [15,  8],
        [ 9, 15],
        [19, 15],
        [ 4,  8],
        [ 3, 15],
        [ 2,  3]]])